### ISSUE TITLE
How to use it? Is there a sample about how to?

### ISSUE THREAD

**Issue by tianchao-haohan** [bondib/kibana-iframe-communicator-plugin#3]
@bondib ,Would you please share a complete html that how to iframe a kibana url?

I used this in html page.
<script>
      var x = document.createElement("IFRAME");
      var iframeURL = "http://kibana-url-example.com";
      x.contentWindow.postMessage('routeRequest###' + iframeUrl, '*');
      x.height = "440";
      x.width = "100%";
      document.body.appendChild(x);
</script>

It doesn't work.

**Comment by ytzlax** [comment]
Hi,
Can you post the real iframeURL ?

**Comment by tianchao-haohan** [comment]
Thanks. I have worked out how to use this.
