### ISSUE TITLE
Add support for kibana 5.x.

### ISSUE THREAD

**Issue by tianchao-haohan** [bondib/kibana-iframe-communicator-plugin#6]
As titled.

**Comment by manuelbernhardt** [comment]
+1 - would be great to be able to use this on kibana 5.x as well

**Comment by ytzlax** [comment]
@tianchao-haohan and @manuelbernhardt @bondib 
look at the pull request #8

**Comment by bondib** [comment]
@ytzlax - can you please add a pull request with this change?
As well, it would be great if you could detect which kibana version is in use  - so we won't have to branch the code and instead have just one version for both kibana 4 and 5.
Thanks again!

**Comment by xycloud** [comment]
any progress for supporting kibana 5.x?

**Comment by ytzlax** [comment]
I already did if(with the detection version that @bondib ask), but I still need to test it, I hope to load it in the next week

**Comment by xycloud** [comment]
any progress?

**Comment by bondib** [comment]
Support added. 
Released as version 5.x + updated installation instructions
